"""scope provider runs to subjects

Revision ID: 048a547ba628
Revises: a8d0dbffeb4e
Create Date: 2026-08-21 23:34:57.261246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '048a547ba628'
down_revision: Union[str, Sequence[str], None] = 'a8d0dbffeb4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_runs', sa.Column('subject_id', sa.UUID(), nullable=True))
    op.alter_column('provider_runs', 'investigation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_provider_runs_subject_id'), 'provider_runs', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'provider_runs', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider_runs', type_='foreignkey')
    op.drop_index(op.f('ix_provider_runs_subject_id'), table_name='provider_runs')
    op.alter_column('provider_runs', 'investigation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('provider_runs', 'subject_id')
    # ### end Alembic commands ###
