"""create investigations and targets

Revision ID: 0eccae7edb65
Revises: 
Create Date: 2026-08-14 21:23:56.155305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eccae7edb65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'QUEUED', 'RUNNING', 'CORRELATING', 'REPORTING', 'COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED', name='investigation_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('investigation_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('USERNAME', 'DOMAIN', 'EMAIL', name='target_type'), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('normalized_value', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('targets')
    op.drop_table('investigations')
    # ### end Alembic commands ###
