"""create subject identities

Revision ID: 79a61117731a
Revises: 6dc20dd93498
Create Date: 2026-08-23 19:03:15.151789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a61117731a'
down_revision: Union[str, Sequence[str], None] = '6dc20dd93498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('profile_url', sa.String(length=1000), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('identifiers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_identities_provider'), 'subject_identities', ['provider'], unique=False)
    op.create_index(op.f('ix_subject_identities_provider_user_id'), 'subject_identities', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_subject_identities_subject_id'), 'subject_identities', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_identities_subject_id'), table_name='subject_identities')
    op.drop_index(op.f('ix_subject_identities_provider_user_id'), table_name='subject_identities')
    op.drop_index(op.f('ix_subject_identities_provider'), table_name='subject_identities')
    op.drop_table('subject_identities')
    # ### end Alembic commands ###
