"""add subject identity model

Revision ID: a8d0dbffeb4e
Revises: 1a6ef8af66c4
Create Date: 2026-08-20 15:48:12.330806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d0dbffeb4e'
down_revision: Union[str, Sequence[str], None] = '1a6ef8af66c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('profile_url', sa.String(length=1000), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('identifiers', sa.JSON(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_provider'), 'subjects', ['provider'], unique=False)
    op.create_index(op.f('ix_subjects_provider_user_id'), 'subjects', ['provider_user_id'], unique=False)
    op.create_index(op.f('ix_subjects_username'), 'subjects', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjects_username'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_provider_user_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_provider'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
